### ISSUE TITLE
Close lightbox on press

### ISSUE THREAD

**Issue by gcandal** [ripe-tech/ripe-components-react-native#150]
##  Description

The `Lightbox` component only currently only closes when pressing the "back" button on the device, which doesn't exist on iOS. Therefore, we must add a way for the user to "escape". Ideally we should have a "close on drag" behavior, but as that might not be easy to implement we should settle for a "close on press".

## Implementation

A simple close button should be place at the top left corner of the image.

![image](https://user-images.githubusercontent.com/3048875/81799730-aa24bc80-9509-11ea-9119-ad3a2ba8c80e.png)

**Comment by joamag** [comment]
@gcandal please post a screen with the current lightbox solution and a scratch of a close button at the top left
