### ISSUE TITLE
Image carrousel component

### ISSUE THREAD

**Issue by beneditomauro** [ripe-tech/ripe-components-react-native#199]
## Rationale

Users should be able to "browse" through a set of images in detail

## Description

Build a component that browses through a list of images highlighting one by one, and using swiping to get to the next one

## Implementation

Build reusing the exisiting ui of [Lightbox](https://github.com/ripe-tech/ripe-components-react-native/blob/master/react/components/atoms/lightbox/lightbox.js) component

### UI/UX design

Something of the likes of:
![ixSau0BpMX](https://user-images.githubusercontent.com/8842023/123784961-e06cf900-d8cf-11eb-9a05-ef5ba144565f.gif)

**Comment by gcandal** [comment]
Where do you believe we could use this right now?

**Comment by joamag** [comment]
@gcandal take good care of this one :P

**Comment by beneditomauro** [comment]
In the attachments screen would be nice to view all the attachments within the app without open the external browser: <br>
<img width="600" alt="ghnfhjnfhjmhgj" src="https://user-images.githubusercontent.com/8842023/123803581-554a2e00-d8e4-11eb-83ff-ada0c2105eaa.png">

And in order-state-transition screen:
<img width="606" alt="fxgnfghn" src="https://user-images.githubusercontent.com/8842023/123803937-a5c18b80-d8e4-11eb-9db6-2f57763e83df.png">
